# DO NOT EDIT THIS FILE. PLEASE USE INSTEAD:
# cbsd jconfig jname=#jname#
relative_path="1";
jname="#jname#";
path="#workdir#/jails/#jname#";
host_hostname="#host_hostname#";
ip4_addr="#ip4_addr#";
mount_devfs="#mount_devfs#";
allow_mount="#allow_mount#";
allow_devfs="#allow_devfs#";
allow_nullfs="#allow_nullfs#";
allow_fusefs="0";
allow_raw_sockets="1";
mount_fstab="#workdir#/jails-fstab/fstab.#jname#";
arch="native";
mkhostsfile="#mkhostsfile#";
devfs_ruleset="#devfs_ruleset#";
ver="#ver#";
basename="";
baserw="#baserw#";
mount_src="#mount_src#";
mount_obj="#mount_obj#";
mount_kernel="#mount_kernel#";
mount_ports="#mount_ports#";
astart="#astart#";
data="#workdir#/jails-data/#jname#-data";
vnet="#vnet#";
nic_hwaddr="0";
applytpl="#applytpl#";
mdsize="#mdsize#";
rcconf="#workdir#/jails-rcconf/rc.conf_#jname#";
floatresolv="#floatresolv#";
zfs_snapsrc="";

exec_poststart="0";
exec_poststop="";
exec_prestart="0";
exec_prestop="0";

exec_master_poststart="0";
exec_master_poststop="0";
exec_master_prestart="0";
exec_master_prestop="0";
pkg_bootstrap="#pkg_bootstrap#";
with_img_helpers="#with_img_helpers#";
runasap="1";
allow_reserved_ports="1";

persist="1";
childrenmax="0";
enforce_statfs="1";
sysrc_enable="#sysrc_enable#"

interface="#interface#";
jailskeldir="#workdir#/share/FreeBSD-jail-skel";
jail_profile="default";
# root password
user_pw_root='#user_pw_root#';
exec_start="/bin/sh /etc/rc"
exec_stop="/bin/sh /etc/rc.shutdown"
emulator="jail"
