# DO NOT EDIT THIS FILE. PLEASE USE INSTEAD:
# cbsd jconfig jname=#jname#
relative_path="1";
jname="#jname#";
path="#workdir#/jails/#jname#";
host_hostname="#host_hostname#";
ip4_addr="#ip4_addr#";
mount_devfs="1";
allow_mount="1";
allow_devfs="1";
allow_nullfs="1";
mount_fstab="#workdir#/jails-fstab/fstab.#jname#";
arch="#arch#";
mkhostsfile="1";
devfs_ruleset="4";
ver="#ver#";
basename="";
baserw="1";
mount_src="0";
mount_obj="0";
mount_kernel="0";
mount_ports="1";
astart="#astart#";
data="#workdir#/jails-data/#jname#-data";
vnet="";
applytpl="1";
mdsize="0";
rcconf="#workdir#/jails-rcconf/rc.conf_#jname#";
floatresolv="1";
zfs_snapsrc="";

exec_poststart="0";
exec_poststop="";
exec_prestart="0";
exec_prestop="0";

exec_master_poststart="0";
exec_master_poststop="0";
exec_master_prestart="0";
exec_master_prestop="0";
pkg_bootstrap="1";
with_img_helpers="";
runasap="0";
interface="#interface#";
jailskeldir="#workdir#/share/FreeBSD-jail-skel";
jail_profile="default";
exec_start="/bin/sh /etc/rc"
exec_stop="/bin/sh /etc/rc.shutdown"
emulator="bhyve";
imgsize="#vm_size#";
vm_cpus="#vm_cpus#";
vm_ram="#vm_ram#";
vm_os_type="#vm_os_type#";
vm_efi="uefi";

#iso_site="";			# must be merged from CBSD profiles
#iso_img="";			# must be merged from CBSD profiles
#register_iso_name=""		# must be merged from CBSD profiles
#register_iso_as=""		# must be merged from CBSD profiles

#vm_hostbridge="hostbridge";	# must be merged from CBSD profiles
#bhyve_flags="";		# must be merged from CBSD profiles
#virtio_type="";		# must be merged from CBSD profiles
gw4="";
vm_os_profile="#vm_os_profile#";
jprofile="default";
swapsize="";
#vm_iso_path="Windows-10-x64";	# must be merged from CBSD profiles
vm_guestfs="#vm_guestfs#";
vm_vnc_port="0";

#bhyve_generate_acpi="1";	# must be merged from CBSD profiles
#bhyve_wire_memory="0";		# must be merged from CBSD profiles
#bhyve_rts_keeps_utc="0";	# must be merged from CBSD profiles
#bhyve_force_msi_irq="0";	# must be merged from CBSD profiles
#bhyve_x2apic_mode="0";		# must be merged from CBSD profiles
#bhyve_mptable_gen="1";		# must be merged from CBSD profiles
#bhyve_ignore_msr_acc="1";	# must be merged from CBSD profiles

cd_vnc_wait="1";
bhyve_vnc_resolution="1024x768";
bhyve_vnc_tcp_bind="127.0.0.1";

